import { Component, useEffect, useState } from 'react';
import { createContext, useContext } from 'react'
import Passage from './Passage.tsx'
import NoteBox from './NoteBox.tsx'
import VideoPlaylist from './VideoPlaylist.tsx'
import type { MenuOption } from './Menu.tsx' // import type important for importing types
import Menu from "./Menu.tsx"

// component types allowed in Layout

type Passage_t = {
    type: "passage"
    id: string
    list: string
}

type NoteBox_t = {
    type: "notebox"
    id: string
}

type VideoPlaylist_t = {
    type: "videoPlaylist"
    id: string
    list: string
}

type Component_t =
    | Passage_t
    | NoteBox_t
    | VideoPlaylist_t

// default layout to use as a fallback
// variety for testing purposes for now
const componentsConfigDefault: Component_t[] = [
    {
        type: "passage",
        id: "section1",
        list: "Psalms.txt",
    },
    {
        type: "passage",
        id: "section2",
        list: "Bible_Chapters.txt",
    },
    {
        type: "notebox",
        id: "section2dfs",
    },
    {
        type: "passage",
        id: "section2ffdafedf",
        list: "Bible_Chapters.txt",
    },
    {
        type: "videoPlaylist",
        id: "section2yjytj",
        list: "Bible_Chapters.txt",
    }
];

function Layout(){
    
    let [componentsConfig, setComponentsConfig] = useState(loadComponentsConfig() || componentsConfigDefault); // loaded || default layout
     
    function loadComponentsConfig()
    {
        const json = localStorage.getItem("componentsConfig");

        // only basic check it has id and type since it is generated by the app anyway
        if(!json) return null;
        try{
            const config = JSON.parse(json);
            if (!Array.isArray(config)) return null;
            // skip if no id or no type
            return config.filter((component) => (component.id && component.type));
        } catch (e)
        {
            console.warn("Invalid stored config. Resorting to default...");
            return null;
        }
    }

    // load the layout from a json object
    function load()
    {    
        setComponentsConfig(prev => {
            const config = loadComponentsConfig() || componentsConfigDefault;
            return config;
        });
    }

    function saveComponentsConfig(config: Component_t[])
    {
        localStorage.setItem("componentsConfig", JSON.stringify(config))
    }

    function moveUp(id: string)
    {
        setComponentsConfig( prev => {
            const index = prev.findIndex(c => c.id === id);
            if (index <= 0 || index === -1) return prev;

            // copy the list
            const newList = [...prev];
            // swap indexes
            let temp = newList[index -1];
            newList[index -1] = newList[index];
            newList[index] = temp;
            // save the config list
            saveComponentsConfig(newList);
            return newList;
        });
    }

    function moveDown(id: string)
    {
        setComponentsConfig( prev => {
            const index = prev.findIndex(c => c.id === id);
            if (index >= prev.length - 1 || index === -1) return prev;

            // copy the list
            const newList = [...prev];
            // swap indexes
            let temp = newList[index +1];
            newList[index +1] = newList[index];
            newList[index] = temp;
            // save the config list
            saveComponentsConfig(newList);
            return newList;
        });
    }

    function deleteComponent(id: string)
    {
        setComponentsConfig( prev => {
            const index = prev.findIndex(c => c.id === id);
            if(index === -1) return prev; // not found
            
            // new list with the old index skipped
            const newList = [...prev.slice(0, index), ...prev.slice(index +1)];
            // save the new config list
            saveComponentsConfig(newList);
            return newList;
        });
    }

    // generate a unique id for a new component
    function generateId()
    {
        let id: string;
        do
        {
            id = "comp_" + Math.random().toString(36).slice(2, 9);
        } while (componentsConfig.some(c => c.id === id));
        return id;
    }

    function addComponent(config: Component_t)
    {
        setComponentsConfig( prev => {
            // add config onto the existing list and then save
            const newList = [...prev, config];
            // save the new config list
            saveComponentsConfig(newList);
            return newList;
        });
    }

    // load config from local storage when layout is first created
    useEffect(() => {
        load();
    }, []);

    // manually saving config instead of useeffect so that invalid loads wont save
    // but this means you do need to save config in the functions which modify it

    // addComponent takes a component_t config object as an argmunet to add to layout
    // these menu options define the configs to pass for each type of component
    let addElementOptions = [
    {
        label: "Passage",
        action: () => {
            addComponent({
                type: "passage",
                id: generateId(),
                list: "Bible_Chapters.txt"
            });
        }
    },
    {
        label: "Psalm",
        action: () => {
            addComponent({
                type: "passage",
                id: generateId(),
                list: "Psalms.txt"
            });
        }
    },
    {
        label: "Note Box",
        action: () => {
            addComponent({
                type: "notebox",
                id: generateId(),
            });
        }
    },
    // video playlist
    {
        label: "Video Playlist",
        action: () => {
            addComponent({
                type: "videoPlaylist",
                id: generateId(),
                list: "PlaceHolder"
            });
        }
    }];

    let elements = <div className='container'>
        {
            componentsConfig.map((c: Component_t) => {

            const layoutOptions = [
                {
                    label: "Move Up",
                    action: () => moveUp(c.id)
                },
                {
                    label: "Move Down",
                    action: () => moveDown(c.id)
                },
                {
                    label: "Delete",
                    action: () => deleteComponent(c.id)
                }
            ];

            // console.log(layoutControls);

            switch(c.type){
                case "passage":
                    return <Passage layoutOptions={layoutOptions} key={c.id}/>;
                case "notebox":
                    return <NoteBox layoutOptions={layoutOptions} key={c.id}/>;
                case "videoPlaylist":
                    return <VideoPlaylist layoutOptions={layoutOptions} key={c.id}/>;
                }
            })
        }
        <section className='add-component-container'>
            <Menu options={addElementOptions}>
                <button className='add-component-button'>+</button>
            </Menu>
        </section>
        </div>

    return elements
}

export default Layout
